config:
  debug: true
  constraints:
    athenz:
      domain:
        name: ""
        prefix: ""
        suffix: ""
      identityprovider:
        service: athenz.identityprovider
    cert:
      expiry:
        defaultmins: 43200
        maxminutes: 43200
      refresh: true
    keys:
      jwks:
        url: http://127.0.0.1:8001/openid/v1/jwks
        cacert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        force_cache: true
        force_cache_duration_seconds: 3600
      apinodes:
        url: http://127.0.0.1:8001/api/v1/nodes
      static: ""
    kubernetes:
      namespaces: []
      serviceaccount:
        names:
          - identityprovider
        token:
          issuer: https://kubernetes.default.svc.cluster.local
          audience: https://kubernetes.default.svc
