---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crypki-softhsm
rules:
  - apiGroups:
      - ""
    resourceNames:
      - crypki-ca
    resources:
      - secrets
    verbs:
      - create
      - update
