---
apiVersion: v1
kind: Service
metadata:
  name: crypki-softhsm
  labels:
    app.kubernetes.io/name: crypki-softhsm
    app.kubernetes.io/instance: crypki-softhsm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: crypki-softhsm
    app.kubernetes.io/instance: crypki-softhsm
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
