#!/usr/bin/env bash
[ "${DEBUG}" = "true" ] && set -x

if [ -z "${ROOT}" ]; then
    export ROOT=/opt/athenz/zms-syncer
fi

# The syncer reads its config as JSON from ${ROOT}/zms_syncer/conf/zms_syncer.conf
# and ${ROOT}/zms_syncer/conf/athenz.conf (hardcoded suffix in Config.java).
# athenz.conf is expected to already exist at this path, generated by an
# initContainer (see kubernetes/athenz-zms-syncer) sharing the same volume.
CONF_DIR="${ROOT}/zms_syncer/conf"
mkdir -p "${CONF_DIR}"
mkdir -p "${STATE_PATH}"
mkdir -p "$(dirname "${TRUSTSTORE_PATH}")"

# Import a custom CA (e.g. this repository's self-signed showcase CA) into
# the JKS truststore the syncer uses for its mTLS connection to ZMS.
if [ -n "${CA_CERT_PEM_PATH}" ]; then
    keytool -list -keystore "${TRUSTSTORE_PATH}" -storepass "${TRUSTSTORE_PASSWORD}" -alias ca >/dev/null 2>&1 || \
        keytool -importcert -noprompt -file "${CA_CERT_PEM_PATH}" -alias ca -keystore "${TRUSTSTORE_PATH}" -storepass "${TRUSTSTORE_PASSWORD}"
fi

envsubst < /opt/athenz/zms-syncer/conf-template/zms_syncer.conf.template > "${CONF_DIR}/zms_syncer.conf"

if [ ! -f "${CONF_DIR}/athenz.conf" ]; then
    echo "Missing ${CONF_DIR}/athenz.conf (expected to be generated by an init step before this container runs)" >&2
    exit 1
fi

ZMS_SYNCER_CLASSPATH="/opt/athenz/zms-syncer/lib/*"
ZMS_SYNCER_BOOTSTRAP_CLASS="com.yahoo.athenz.zms_aws_domain_syncer.ZmsSyncer"

### !!! P.S. cannot quote JAVA_OPTS !!!
### reference: https://github.com/koalaman/shellcheck/wiki/SC2086
exec java -classpath "${ZMS_SYNCER_CLASSPATH}" ${JAVA_OPTS} ${ZMS_SYNCER_BOOTSTRAP_CLASS}
