---
apiVersion: v1
kind: Service
metadata:
  name: rustfs
  labels:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/instance: rustfs
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/instance: rustfs
  ports:
    - name: s3-api
      port: 9000
      targetPort: s3-api
      protocol: TCP
    - name: console
      port: 9001
      targetPort: console
      protocol: TCP
