---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - serviceaccount.yaml

generatorOptions:
  disableNameSuffixHash: true

#secretGenerator:
#- files:
#  - ca.cert.pem=certs/ca.cert.pem
#  name: athenz-cacert
#  type: Opaque

configMapGenerator:
  - name: k8sclient-sia
    envs:
      - athenz-sia/athenz-sia.env
  - name: k8sclient-envoy
    files:
      - config.yaml=envoy/config.yaml
      - identity_sds.yaml=envoy/identity_sds.yaml
      - role_sds.yaml=envoy/role_sds.yaml
      - ca_sds.yaml=envoy/ca_sds.yaml

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: k8sclient-sia
      fieldpath: data.SERVICEACCOUNT
    targets:
      - select:
          version: v1
          kind: ServiceAccount
          name: k8sclient-serviceaccount
        fieldPaths:
          - metadata.name
        options:
          create: true
      - select:
          version: v1
          kind: Deployment
          name: k8sclient-deployment
        fieldPaths:
          - spec.template.spec.serviceAccountName
        options:
          create: true
