---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml

generatorOptions:
  disableNameSuffixHash: true

#secretGenerator:
#- files:
#  - ca.cert.pem=certs/ca.cert.pem
#  name: athenz-cacert
#  type: Opaque

configMapGenerator:
  - name: identityprovider-sia
    envs:
      - athenz-sia/athenz-sia.env
  - name: identityprovider-envoy
    files:
      - config.yaml=envoy/config.yaml
      - identity_sds.yaml=envoy/identity_sds.yaml
  - name: athenz-identityprovider
    envs:
      - athenz-identityprovider-policy/athenz-identityprovider.env
  - name: identityprovider-config
    files:
      - config.yaml=athenz-identityprovider-policy/config.yaml
  - name: identityprovider-policy
    files:
      - system.authz.rego=athenz-identityprovider-policy/policy/system.authz.rego
      - identityprovider.rego=athenz-identityprovider-policy/policy/identityprovider.rego
      - system.log.rego=athenz-identityprovider-policy/policy/system.log.rego
      - config.yaml=athenz-identityprovider-policy/policy/config.yaml

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: identityprovider-sia
      fieldpath: data.SERVICEACCOUNT
    targets:
      - select:
          version: v1
          kind: ServiceAccount
          name: identityprovider-serviceaccount
        fieldPaths:
          - metadata.name
        options:
          create: true
      - select:
          version: v1
          kind: Deployment
          name: identityprovider-deployment
        fieldPaths:
          - spec.template.spec.serviceAccountName
        options:
          create: true
      - select:
          version: v1
          kind: Deployment
          name: identityprovider-sia
        fieldPaths:
          - spec.template.spec.serviceAccountName
        options:
          create: true
