---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- pvc.yaml
- cronjob.yaml

secretGenerator:
- files:
  - zms-syncer.private.pem=keys/zms-syncer.private.pem
  - zms-syncer.public.pem=keys/zms-syncer.public.pem
  name: athenz-zms-syncer-keys
  type: Opaque
- files:
  - zms-syncer.cert.pem=certs/zms-syncer.cert.pem
  name: athenz-zms-syncer-certs
  type: Opaque
- files:
  - ca.cert.pem=certs/ca.cert.pem
  name: athenz-cacert
  type: Opaque
- files:
  - athenz_admin.private.pem=keys/athenz_admin.private.pem
  - athenz_admin.cert.pem=certs/athenz_admin.cert.pem
  name: athenz-admin-keys
  type: Opaque

images:
- name: ghcr.io/ctyano/athenz-zms-syncer:latest
  newName: ghcr.io/ctyano/athenz-zms-syncer
  newTag: latest
- name: ghcr.io/ctyano/athenz-cli:latest
  newName: ghcr.io/ctyano/athenz-cli
  newTag: latest
