---
apiVersion: v1
kind: Service
metadata:
  name: athenz-mcp-server
  labels:
    app.kubernetes.io/name: athenz-mcp-server
    app.kubernetes.io/instance: athenz-mcp-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: athenz-mcp-server
    app.kubernetes.io/instance: athenz-mcp-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
