apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- serviceaccount.yaml

generatorOptions:
  disableNameSuffixHash: true

#secretGenerator:
#- files:
#  - ca.cert.pem=certs/ca.cert.pem
#  name: athenz-cacert
#  type: Opaque

configMapGenerator:
- envs:
  - athenz-sia/athenz-sia.env
  name: authorizer-sia
- files:
  - config.yaml=envoy/config.yaml
  - identity_sds.yaml=envoy/identity_sds.yaml
  - role_sds.yaml=envoy/role_sds.yaml
  - ca_sds.yaml=envoy/ca_sds.yaml
  name: authorizer-envoy

replacements:
- source:
    fieldPath: data.SERVICEACCOUNT
    kind: ConfigMap
    name: authorizer-sia
    version: v1
  targets:
  - fieldPaths:
    - metadata.name
    options:
      create: true
    select:
      kind: ServiceAccount
      name: authorizer-serviceaccount
      version: v1
  - fieldPaths:
    - spec.template.spec.serviceAccountName
    options:
      create: true
    select:
      kind: Deployment
      name: authorizer-deployment
      version: v1
images:
- name: ghcr.io/ctyano/athenz-cli:latest
  newName: ghcr.io/ctyano/athenz-cli
  newTag: source-AthenZ-athenz-e2eb8c5-v1.12.45-SNAPSHOT-e2eb8c52b
