apiVersion: apps/v1
kind: Deployment
metadata:
  name: athenz-zts-server
spec:
  template:
    spec:
      volumes:
        - name: vault-approle
          secret:
            secretName: vault-approle
            optional: true
      containers:
        - name: athenz-zts-server
          env:
            - name: ATHENZ__ZTS__VAULT__APPROLE_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle
                  key: role_id
            - name: ATHENZ__ZTS__VAULT__APPROLE_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle
                  key: secret_id
          volumeMounts:
            - name: vault-approle
              mountPath: /var/run/athenz/vault
              readOnly: true
