apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- service.yaml
- statefulset.yaml

images:
- name: ghcr.io/ctyano/athenz-db:latest
  newName: ghcr.io/ctyano/athenz-db
  newTag: source-AthenZ-athenz-e2eb8c5-v1.12.45-SNAPSHOT-e2eb8c52b
