---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-deployment
  labels:
    app: oauth2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-deployment
  template:
    metadata:
      labels:
        app: oauth2-deployment
    spec:
      volumes:
        - name: athenz-idp-keys
          secret:
            secretName: athenz-idp-keys
            defaultMode: 0555
            items:
              - key: idp.private.pem
                path: idp.private.pem
        - name: athenz-idp-certs
          secret:
            secretName: athenz-idp-certs
            defaultMode: 0555
            items:
              - key: idp.cert.pem
                path: idp.cert.pem
        - name: dex-config
          configMap:
            name: dex-config
        - name: envoy-config
          configMap:
            name: oauth2-envoy-config
        - name: athenz-cacert
          secret:
            secretName: athenz-cacert
            defaultMode: 0555
            items:
              - key: ca.cert.pem
                path: ca-certificates.crt
      containers:
        - name: dex
          image: docker.io/dexidp/dex:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: dex
              containerPort: 5556
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: dex-config
              mountPath: /etc/dex/config.docker.yaml
              subPath: config.docker.yaml
            - name: athenz-idp-keys
              mountPath: /opt/athenz/dex/keys
              readOnly: true
            - name: athenz-idp-certs
              mountPath: /opt/athenz/dex/certs
              readOnly: true
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 50m
        - name: envoy
          image: ghcr.io/ctyano/certsigner-envoy:latest
          imagePullPolicy: IfNotPresent
          command:
            - envoy
            - -c
            - /etc/envoy/envoy.yaml
            - -l
            - debug
          ports:
            - name: envoy
              containerPort: 10000
              protocol: TCP
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
        - name: athenz-user-cert
          image: ghcr.io/ctyano/athenz-user-cert:latest
          imagePullPolicy: IfNotPresent
          command:
            - tail
            - -f
          volumeMounts:
            - name: athenz-cacert
              mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: ca-certificates.crt
              readOnly: true
