---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: dex-config
    files:
      - config.docker.yaml=dex/config.yaml
  - name: envoy-config
    files:
      - envoy.yaml=envoy/config.yaml
