---
apiVersion: v1
kind: Service
metadata:
  name: oauth2
  labels:
    app: oauth2-service
spec:
  type: ClusterIP
  selector:
    app: oauth2-deployment
  ports:
    - name: https
      port: 443
      targetPort: https
    - name: mtls
      port: 4443
      targetPort: mtls
