# athenz-oauth2
---
admin:
  access_log:
    - name: access_log_file
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
        path: "/dev/stdout"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
node:
  id: envoy-0
  cluster: envoy-cluster
static_resources:
  listeners:
    - name: localhost_listener
      address:
        socket_address:
          protocol: TCP
          address: ::FFFF:127.0.0.1
          ipv4_compat: true
          port_value: 8080
      filter_chains: &localhost_filter_chains
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: localhost_proxy_prefix
                access_log: &access_log
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                route_config: &localhost_route_config
                  name: localhost_proxy_route
                  virtual_hosts:
                    - name: localhost_proxy_hosts
                      domains:
                        # Only a single wildcard domain is permitted in route https_proxy_route
                        - "*"
                      typed_per_filter_config:
                        envoy.filters.http.ext_authz:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                          check_settings:
                            context_extensions:
                              virtual_host: localhost_proxy_hosts
                      routes: &localhost_routes
                        - match:
                            path_separated_prefix: "/status"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "This is server ingress proxy."
                          response_headers_to_add:
                            - header:
                                key: x-athenz-method
                                value: "%REQ(:METHOD)%"
                            - header:
                                key: x-athenz-path
                                value: "%REQ(:PATH)%"
                          typed_per_filter_config: &filters_disabled
                            envoy.filters.http.ext_authz.authorization: &ext_authz_authorizationsidecar_disabled
                              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                              disabled: true
                        - match:
                            path_separated_prefix: "/zms/v1"
                          route:
                            cluster: zms
                            auto_host_rewrite: true
                          typed_per_filter_config: *filters_disabled
                        - match:
                            path_separated_prefix: "/zts/v1"
                          route:
                            cluster: zts
                            auto_host_rewrite: true
                          typed_per_filter_config: *filters_disabled
                        - match:
                            path_separated_prefix: "/oauth2"
                          route:
                            cluster: echoserver
                            prefix_rewrite: "/echoserver"
                            auto_host_rewrite: true
                          request_headers_to_add: &request_headers_to_add
                            - header:
                                key: x-athenz-sni
                                value: "%REQUESTED_SERVER_NAME%"
                            - header:
                                key: x-athenz-certificate-subject
                                value: "%DOWNSTREAM_PEER_SUBJECT%"
                            - header:
                                key: x-athenz-certificate-issuer
                                value: "%DOWNSTREAM_PEER_ISSUER%"
                            - header:
                                key: x-athenz-certificate-san-uri
                                value: "%DOWNSTREAM_PEER_URI_SAN%"
                            - header:
                                key: x-athenz-certificate-v-start
                                value: "%DOWNSTREAM_PEER_CERT_V_START%"
                            - header:
                                key: x-athenz-certificate-v-end
                                value: "%DOWNSTREAM_PEER_CERT_V_END%"
                            - header:
                                key: x-athenz-certificate
                                value: "%DOWNSTREAM_PEER_CERT%"
                            - header:
                                key: x-athenz-proxy
                                value: "ingress envoy with extauthz filter"
                        - match:
                            prefix: "/echoserver"
                          route:
                            cluster: echoserver
                          request_headers_to_add: *request_headers_to_add
                          typed_per_filter_config: *filters_disabled
                        - match:
                            prefix: "/"
                          route:
                            cluster: envoy_admin
                          typed_per_filter_config: *filters_disabled
                http_filters: &localhost_http_filters
                  # Oauth2 External Authorization
                  - name: envoy.filters.http.ext_authz.oauth2
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      # https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html#extensions-filters-http-ext-authz-v3-httpservice
                      http_service:
                        server_uri:
                          uri: 127.0.0.1:4180
                          cluster: oauth2-proxy
                          timeout: 5s
                        authorization_request:
                          headers_to_add:
                            - key: x-auth-request-redirect
                              value: https://dexidp/dex/auth
                          allowed_headers:
                            patterns:
                              - safe_regex:
                                  google_re2: {}
                                  regex: ".*"
                        authorization_response:
                          allowed_upstream_headers:
                            patterns:
                              - prefix: "x-"
                      with_request_body:
                        max_request_bytes: 1024
                      transport_api_version: V3
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    - name: mtls_listener
      address:
        socket_address:
          protocol: TCP
          address: ::FFFF:0.0.0.0
          ipv4_compat: true
          port_value: 4443
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: mtls_proxy_prefix
                access_log: *access_log
                route_config: *localhost_route_config
                http_filters: *localhost_http_filters
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context: &common_tls_context
                tls_certificate_sds_secret_configs: &tls_certificate_sds_secret_configs_identity
                  - name: identity_sds
                    sds_config:
                      path_config_source:
                        path: /etc/envoy/identity_sds.yaml
                      resource_api_version: V3
                validation_context_sds_secret_config: &validation_context_sds_secret_config_ca
                  name: ca_sds
                  sds_config:
                    path_config_source:
                      path: /etc/envoy/ca_sds.yaml
                    resource_api_version: V3
              require_client_certificate: true
    - name: https_listener
      address:
        socket_address:
          protocol: TCP
          address: ::FFFF:0.0.0.0
          ipv4_compat: true
          port_value: 443
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: https_proxy_prefix
                access_log: *access_log
                route_config: *localhost_route_config
                http_filters: *localhost_http_filters
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificate_sds_secret_configs: *tls_certificate_sds_secret_configs_identity
  clusters:
    - name: envoy_admin
      connect_timeout: 0.25s
      type: STATIC # LOGICAL_DNS or STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: envoy_admin
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 9901
    - name: envoy_localhost
      connect_timeout: 0.25s
      type: STATIC # LOGICAL_DNS or STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: envoy_localhost
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080
    - name: zms
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: zms
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: athenz-zms-server.athenz
                      port_value: 4443
      transport_socket: &transport_socket
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context: *common_tls_context
    - name: zts
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: zts
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: athenz-zts-server.athenz
                      port_value: 4443
      transport_socket: *transport_socket
    - name: echoserver
      connect_timeout: 0.25s
      type: STATIC # LOGICAL_DNS or STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: echoserver
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 3000
