---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegeta
  labels:
    app: vegeta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vegeta
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vegeta
    spec:
      restartPolicy: Always
      volumes:
        - name: data
          emptyDir: {}
        - name: athenz-cacert
          secret:
            secretName: athenz-cacert
            defaultMode: 0555
            items:
              - key: ca.cert.pem
                path: ca-certificates.crt
      containers:
        - name: vegeta
          image: ghcr.io/ctyano/docker-vegeta:latest
          imagePullPolicy: IfNotPresent
          command:
            - tail
            - -f
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: athenz-cacert
              mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: ca-certificates.crt
              readOnly: true
